name: Continuous Integration on push requests

on:
  push:
    branches:
      - main

jobs:
  static-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm install
      - run: npm run lint
      - run: npm run test